apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-2
spec:
  parallelism: 2
  template:
    metadata:
      name: job-wq-2
    spec:
      containers:
      - name: c
        image: 197441620132.dkr.ecr.us-west-2.amazonaws.com/job-wq-2
      restartPolicy: OnFailure
